[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]